export default {
	newTitle: 'Start-up Nations',
	newSubtitle: 'Disrupting Modern Governance',
	markdown: '# Quicquam male trahi ensem\n\n## Partus visum anxia me recessit videt\n\nLorem markdownum, meo colorem Iovis super vellem tellus capta! Dixit erat cuncta\nquamvis tuum, caput, malignas utroque.\n\n1. Per hic copia ferunt est prodigiosa subdita\n2. Ambigui pro vixisti a oculos Orpheus herba\n3. Pagasaeae et priscum animi eram\n4. Dite sidus viaeque vestigia et carpe traxit\n5. Sentit Cephisius raptusque credidit Iove nox\n6. Extinctum inquit ille thalamos ora miserabile vestra\n\n## Sororis quid\n\nMari mediam me tibi. Omnia incepta ministrarum, axem favilla magno Iovis. Pater\nse fama, subiit summo texta longius.\n\nHumi tauri, quas undae vulnere deiectoque obductos, hic ego sorores saepe humo\npocula referente. Gratia sed meo quid nec sublimis sensit Pulchrior quoque\ninculpata nostro diversa ipsa quae. Lacrimis igitur gaudia a signa cum septem\nardebat fores. Enim da Myscelus stricto: vos rupta si denique corpore, triplici\nDryasque, sono!\n\n## Succumbere si tamen tamen spatium\n\nFulminis tumulum capit: mihi dure retinete casside, sed se angues adnuit semper.\nSaxificos fulmen praescius inpono, adspergit inquire Hesperio matura lacrimasque\nresolutum. Cephenum Amoris de percussis reluxit inde admovit: munere tu nova ego\nbellis eum ergo nato, in celebrant.\n\n## Veniente sociasque ira\n\nSequenti melior at illi imitatus insigne velut seu neque frigore. Minervae\npendens, Stygio videri ferre; magna pede devastata illa.\n\n## Toto tenuerunt\n\nExitus mente ea orbes, et caruisse raris, et quod non laevo nec et dicitur\ngenitum nepotem modo. Paulum sidoniae valuere culpam, cum dixi fuerant adspicit\nLucina quod cursus inprudens fratres tacito: ore, dotaliaque. Aurum totiens\nCastrumque visus planxitque dixit, montibus tamen, dies, opto nolle. Cum margine\ngregis refert fluminea tum vicinia vidisset raptam, et genitore secutus rupta.\n\n1. Amplexuque instar\n2. Thoactes et Iubam scelerata capax ingemis hostis\n3. Cuius quem\n4. Vibrata cervice hic ullo Latiis erat manare\n5. Voluptas postquam adopertaque manum mortalia triumphos labique\n\nVerus velut, rutilos dissimulare prisca licentia et saxa, ululatibus lacus tuae\nlacrimis. Iam metus sub natus gemmis invidiosa dixit trabes astra atque, et.',
	slug: 'martin-foo',
	description: 'Start-up nations – Disrupting modern governance',
	title: 'Martin Foo',
	heroImage: 'martin',
	essayPDF: 'http://www.symposium.org/sites/default/files/Essay_MartinFoo.pdf',
	audience: 'dogs, cats, lizards, birds, whales, iguanas, encyclopedia'
};
